{
  const global = typeof window !== "undefined" ? window : globalThis;
  const Animotion = global.Animotion || (global.Animotion = {});

  Animotion.selectors = {
    sourceCanvas: "#sourceCanvas",
    previewCanvas: "#previewCanvas",
    imageInput: "#imageInput",
    nextImageInput: "#nextImageInput",
    loadLookismPreset: "#loadLookismPreset",
    lookismPresetStatus: "#lookismPresetStatus",
    generateDemoGengaCut: "#generateDemoGengaCut",
    applyDemoGengaMotion: "#applyDemoGengaMotion",
    demoGengaStatus: "#demoGengaStatus",
    sourceStatus: "#sourceStatus",
    previewStatus: "#previewStatus",
    selectionTool: "#selectionTool",
    partType: "#partType",
    partName: "#partName",
    capturePart: "#capturePart",
    applyOutline: "#applyOutline",
    finishSelection: "#finishSelection",
    clearSelection: "#clearSelection",
    sourceZoom: "#sourceZoom",
    zoomOut: "#zoomOut",
    zoomReset: "#zoomReset",
    zoomIn: "#zoomIn",
    guideParts: "#guideParts",
    motionTemplate: "#motionTemplate",
    currentFrame: "#currentFrame",
    frameLabel: "#frameLabel",
    insertKeyframe: "#insertKeyframe",
    deleteKeyframe: "#deleteKeyframe",
    keyframeStatus: "#keyframeStatus",
    impactExaggerationEnabled: "#impactExaggerationEnabled",
    impactExaggerationStatus: "#impactExaggerationStatus",
    cutsceneMotionStatus: "#cutsceneMotionStatus",
    autoAnticipation: "#autoAnticipation",
    motionStrength: "#motionStrength",
    backgroundOpacity: "#backgroundOpacity",
    impactReferenceOpacity: "#impactReferenceOpacity",
    sourcePanelX: "#sourcePanelX",
    sourcePanelY: "#sourcePanelY",
    sourcePanelScale: "#sourcePanelScale",
    impactPanelX: "#impactPanelX",
    impactPanelY: "#impactPanelY",
    impactPanelScale: "#impactPanelScale",
    separateCharacter: "#separateCharacter",
    playPause: "#playPause",
    exportWebm: "#exportWebm",
    partsList: "#partsList",
    emptyInspector: "#emptyInspector",
    partInspector: "#partInspector",
    editName: "#editName",
    editType: "#editType",
    editHumanRole: "#editHumanRole",
    editParent: "#editParent",
    pivotEditTarget: "#pivotEditTarget",
    autoPlaceArmHandles: "#autoPlaceArmHandles",
    autoPlaceArmHandlesStatus: "#autoPlaceArmHandlesStatus",
    pivotXLabel: "#pivotXLabel",
    pivotYLabel: "#pivotYLabel",
    pivotX: "#pivotX",
    pivotY: "#pivotY",
    jointXLabel: "#jointXLabel",
    jointYLabel: "#jointYLabel",
    jointX: "#jointX",
    jointY: "#jointY",
    handTipXLabel: "#handTipXLabel",
    handTipYLabel: "#handTipYLabel",
    handTipX: "#handTipX",
    handTipY: "#handTipY",
    editOrder: "#editOrder",
    editAlpha: "#editAlpha",
    editHidden: "#editHidden",
    partTransformControls: "#partTransformControls",
    copyPart: "#copyPart",
    flipPartHorizontal: "#flipPartHorizontal",
    rotatePartDegrees: "#rotatePartDegrees",
    rotatePartCounterClockwise: "#rotatePartCounterClockwise",
    rotatePartClockwise: "#rotatePartClockwise",
    supplementalPartEditor: "#supplementalPartEditor",
    supplementalPartX: "#supplementalPartX",
    supplementalPartY: "#supplementalPartY",
    supplementalPartW: "#supplementalPartW",
    supplementalPartH: "#supplementalPartH",
    supplementalMaskScale: "#supplementalMaskScale",
    motionX: "#motionX",
    motionY: "#motionY",
    motionRotate: "#motionRotate",
    motionScaleY: "#motionScaleY",
    motionJointX: "#motionJointX",
    motionJointY: "#motionJointY",
    motionPhase: "#motionPhase",
    resetPartMotion: "#resetPartMotion",
    deletePart: "#deletePart",
    undoCommand: "#undoCommand",
    redoCommand: "#redoCommand",
    saveRig: "#saveRig",
    loadRig: "#loadRig",
  };

  Animotion.config = {
    rigVersion: 2,
    minShapeSize: 4,
    hitTolerancePx: 12,
    lassoPointSpacing: 2,
    zoomStep: 1.25,
    wheelZoomStep: 1.12,
    exportDurationMs: 3200,
    minWebmDurationMs: 1200,
    exportFps: 30,
    timelineFrames: 120,
    timelineFps: 24,
  };

  Animotion.tool = {
    edit: "edit",
    rect: "rect",
    ellipse: "ellipse",
    lasso: "lasso",
    polygon: "polygon",
  };

  Animotion.dragKind = {
    panSource: "pan-source",
    drawBox: "draw-box",
    drawLasso: "draw-lasso",
    editSelection: "edit-selection",
    editPart: "edit-part",
  };

  Animotion.shapeKind = {
    rect: "rect",
    ellipse: "ellipse",
    lasso: "lasso",
    polygon: "polygon",
  };

  Animotion.partTypeLabels = {
    head: "머리",
    body: "몸통",
    spine: "스파인",
    arm: "팔",
    leg: "다리",
    hair: "머리카락",
    eye: "눈",
    mouth: "입",
    prop: "소품",
  };
}
